version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm"
    directory: "/cms"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm"
    directory: "/content"
    schedule:
      interval: "weekly"
