name: Build

on: workflow_dispatch

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    environment: client-staging
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      IOS_APPLE_ID: ${{ secrets.IOS_APPLE_ID }}
      IOS_APP_STORE_TEAM_ID: ${{ secrets.IOS_APP_STORE_TEAM_ID }}
      IOS_DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.IOS_DEVELOPER_PORTAL_TEAM_ID }}
      IOS_BUNDLE_IDENTIFIER: ${{ secrets.IOS_BUNDLE_IDENTIFIER }}
      IOS_SCHEME: ${{ secrets.IOS_SCHEME }}

      ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
      ANDROID_FLAVOR: ${{ secrets.ANDROID_FLAVOR }}
      ANDROID_GOOGLE_PLAY_SERVICE_FILE: ./google-play-service.json

    steps:
      - uses: actions/checkout@v3

      - name: Use Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create Dotenv File
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: 'ENV_'
          directory: 'client/'
        env:
          ENV_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          ENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENV_IOS_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.IOS_CODE_PUSH_DEPLOYMENT_KEY }}
          ENV_ANDROID_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.ANDROID_CODE_PUSH_DEPLOYMENT_KEY }}
          ENV_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}

      - name: Create google-play-service.json
        working-directory: ./client
        run: echo "${{ secrets.ANDROID_GOOGLE_PLAY_SERVICE_FILE }}" > $ANDROID_GOOGLE_PLAY_SERVICE_FILE

      - name: Cache Client Dependencies
        id: cache-client-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: client-node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Prepare $GIT_COMMIT_SHORT
        working-directory: ./client
        run: ./scripts/getGitCommitShort.sh >> $GITHUB_ENV

      - uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'android app'
          subdirectory: ./client/fastlane
