name: Build

on: workflow_dispatch

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      skipClientVersionBumpTest: true

  build-android-staging:
    name: Android Staging
    needs: test
    concurrency: build-android-production
    uses: ./.github/workflows/build-android.yml
    with:
      environment: staging
      branch: ${{ github.ref_name }}
    secrets: inherit

  build-android-production:
    name: Android Production
    needs: test
    concurrency: build-android-staging
    uses: ./.github/workflows/build-android.yml
    with:
      environment: production
      branch: ${{ github.ref_name }}
    secrets: inherit

  build-ios-staging:
    name: iOS Staging
    needs: test
    concurrency: build-ios-staging
    uses: ./.github/workflows/build-ios.yml
    with:
      environment: staging
      branch: ${{ github.ref_name }}
    secrets: inherit

  build-ios-production:
    name: iOS Production
    needs: test
    concurrency: build-ios-production
    uses: ./.github/workflows/build-ios.yml
    with:
      environment: production
      branch: ${{ github.ref_name }}
    secrets: inherit
