name: iOS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  ios:
    name: Build
    runs-on: macos-12
    environment: client-${{ inputs.environment }}
    env:
      CI: github

      SOURCEMAPS_DIR: ./build/sourcemaps

      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      DOTENV_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      DOTENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      DOTENV_IOS_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.IOS_CODE_PUSH_DEPLOYMENT_KEY }}
      DOTENV_ANDROID_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.ANDROID_CODE_PUSH_DEPLOYMENT_KEY }}
      DOTENV_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}

      IOS_APPLE_ID: ${{ secrets.IOS_APPLE_ID }}
      IOS_APP_STORE_TEAM_ID: ${{ secrets.IOS_APP_STORE_TEAM_ID }}
      IOS_DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.IOS_DEVELOPER_PORTAL_TEAM_ID }}
      IOS_BUNDLE_IDENTIFIER: ${{ secrets.IOS_BUNDLE_IDENTIFIER }}
      IOS_SCHEME: ${{ secrets.IOS_SCHEME }}
      IOS_APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.IOS_APP_STORE_CONNECT_API_ISSUER_ID }}
      IOS_APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY_ID }}
      IOS_APP_STORE_CONNECT_API_KEY_FILE: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY_FILE }}
      MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Add keys repo access key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.KEYS_REPO_ACCESS_KEY }}

      - name: Create Dotenv File
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: 'DOTENV_'
          directory: './client'

      - name: Create GoogleService-Info.plist
        working-directory: ./client/ios/Supporting
        run: echo "${{ secrets.IOS_GOOGLE_SERVICE_PLIST_FILE }}" > ./$IOS_SCHEME/GoogleService-Info.plist

      - name: Prepare Source Maps Directory
        working-directory: ./client
        run: mkdir -p $SOURCEMAPS_DIR

      - name: Prepare $GIT_COMMIT_SHORT
        working-directory: ./client
        run: ./scripts/getGitCommitShort.sh >> $GITHUB_ENV

      - name: Cache Client Dependencies
        id: cache-client-node-modules-pods
        uses: actions/cache@v2
        with:
          path: |
            ./client/node_modules
            ./client/ios/Pods
          key: client-node-modules-pods-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules-pods.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Install Fastlane Dependencies
        working-directory: ./client/fastlane
        run: bundle install

      - name: Download Daily Bitcode
        working-directory: ./client
        run: ./node_modules/@daily-co/react-native-webrtc/tools/downloadBitcode.sh

      - name: Build Content
        working-directory: ./content
        run: yarn build

      #- name: Build & Upload App
      #  working-directory: ./client/fastlane
      #  run: bundle exec fastlane ios app
      #
      #- name: Upload Logs
      #  uses: actions/upload-artifact@v3
      #  if: failure()
      #  with:
      #    name: ios-build-logs
      #    path: /Users/runner/Library/Logs/gym/*

      - name: Generate Source Map
        working-directory: ./client
        run: |
          yarn react-native bundle
          --dev false
          --entry-file index.js
          --platform ios
          --bundle-output $SOURCEMAPS_DIR/main.jsbundle
          --sourcemap-output $SOURCEMAPS_DIR/main.jsbundle.map

      - name: Upload Source Map to Sentry
        working-directory: ./client
        run: >
          yarn sentry-cli releases
          files $GIT_COMMIT_SHORT
          upload-sourcemaps
          --dist ${{ inputs.environment }}
          --strip-prefix $PWD
          $SOURCEMAPS_DIR

      - name: Associate Commits to Sentry Release
        working-directory: ./client
        run: yarn sentry-cli releases set-commits --auto $GIT_COMMIT_SHORT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: iOS native version bump on ${{ inputs.branch }} (auto generated)
          commit-message: Native Version Bump
          branch: ${{ inputs.branch }}-ios-native-version-bump
