name: Build

on: workflow_dispatch

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    environment: client-staging
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      IOS_APPLE_ID: ${{ secrets.IOS_APPLE_ID }}
      IOS_APP_STORE_TEAM_ID: ${{ secrets.IOS_APP_STORE_TEAM_ID }}
      IOS_DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.IOS_DEVELOPER_PORTAL_TEAM_ID }}
      IOS_BUNDLE_IDENTIFIER: ${{ secrets.IOS_BUNDLE_IDENTIFIER }}
      IOS_SCHEME: ${{ secrets.IOS_SCHEME }}

      ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
      ANDROID_FLAVOR: ${{ secrets.ANDROID_FLAVOR }}
      ANDROID_UPLOAD_STORE_PASSWORD: ${{ secrets.ANDROID_UPLOAD_STORE_PASSWORD }}
      ANDROID_UPLOAD_KEY_PASSWORD: ${{ secrets.ANDROID_UPLOAD_KEY_PASSWORD }}
      ANDROID_GOOGLE_PLAY_SERVICE_FILE: ./google-play-service.json

    steps:
      - uses: actions/checkout@v3

      - name: Use Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install bundle
        run: gem install bundle

      - name: Create Dotenv File
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: 'ENV_'
          directory: './client'
        env:
          ENV_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          ENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENV_IOS_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.IOS_CODE_PUSH_DEPLOYMENT_KEY }}
          ENV_ANDROID_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.ANDROID_CODE_PUSH_DEPLOYMENT_KEY }}
          ENV_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}

      - name: Create google-play-service.json
        working-directory: ./client/fastlane
        run: |
          cat > $ANDROID_GOOGLE_PLAY_SERVICE_FILE << EOL
          ${{ secrets.ANDROID_GOOGLE_PLAY_SERVICE_FILE }}
          EOL

      - name: Create google-services.json
        working-directory: ./client/android/app/src
        run: |
          cat > ./$ANDROID_FLAVOR/google-services.json << EOL
          ${{ secrets.ANDROID_GOOGLE_SERVICES_FILE }}
          EOL

      - name: Create release.keystore
        working-directory: ./client/android/app
        run: |
          cat > ./release.keystore << EOL
          ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
          EOL

      - name: Cache Client Dependencies
        id: cache-client-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: client-node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Install Fastlane Dependencies
        working-directory: ./client/fastlane
        run: bundle install

      - name: Build Content
        working-directory: ./content
        run: yarn build

      - name: Prepare $GIT_COMMIT_SHORT
        working-directory: ./client
        run: ./scripts/getGitCommitShort.sh >> $GITHUB_ENV

      - name: Build Android App
        working-directory: ./client/fastlane
        run: bundle exec fastlane android app

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Native Version Bump (auto generated)
          commit-message: Native Version Bump
          branch: native-version-bump
          delete-branch: true
