name: Build

on: workflow_dispatch

jobs:
  build-android-staging:
    name: Android Staging
    concurrency: build-android-staging
    uses: ./.github/workflows/build-android.yml
    with:
      environment: staging
      branch: ${{ github.ref_name }}
    secrets: inherit

  build-android-production:
    name: Android Production
    concurrency: build-android-production
    needs: build-android-staging # Run this sequentially since they bumps the same version code
    uses: ./.github/workflows/build-android.yml
    with:
      environment: production
      branch: ${{ github.ref_name }}
    secrets: inherit
