name: iOS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  android:
    name: Build
    runs-on: macos-latest
    environment: client-${{ inputs.environment }}
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      DOTENV_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      DOTENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      DOTENV_IOS_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.IOS_CODE_PUSH_DEPLOYMENT_KEY }}
      DOTENV_ANDROID_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.ANDROID_CODE_PUSH_DEPLOYMENT_KEY }}
      DOTENV_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}

      IOS_APPLE_ID: ${{ secrets.IOS_APPLE_ID }}
      IOS_APP_STORE_TEAM_ID: ${{ secrets.IOS_APP_STORE_TEAM_ID }}
      IOS_DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.IOS_DEVELOPER_PORTAL_TEAM_ID }}
      IOS_BUNDLE_IDENTIFIER: ${{ secrets.IOS_BUNDLE_IDENTIFIER }}
      IOS_SCHEME: ${{ secrets.IOS_SCHEME }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Create Dotenv File
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: 'ENV_'
          directory: './client'

      - name: Create GoogleService-Info.plist
        working-directory: ./client/ios/Supporting
        run: echo "${{ secrets.IOS_GOOGLE_SERVICE_PLIST_FILE }}" > ./$IOS_SCHEME/GoogleService-Info.plist

      - name: Prepare $GIT_COMMIT_SHORT
        working-directory: ./client
        run: ./scripts/getGitCommitShort.sh >> $GITHUB_ENV

      - name: Cache Client Dependencies
        id: cache-client-node-modules-pods
        uses: actions/cache@v2
        with:
          path: |
            ./client/node_modules
            ./client/ios/Pods
          key: client-node-modules-pods-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules-pods.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Install Fastlane Dependencies
        working-directory: ./client/fastlane
        run: bundle install

      - name: Build Content
        working-directory: ./content
        run: yarn build
#      - name: Build iOS App
#        working-directory: ./client/fastlane
#        run: bundle exec fastlane android app
#
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v4
#        with:
#          title: Native version bump on ${{ inputs.branch }} (auto generated)
#          commit-message: Native Version Bump
#          branch: ${{ inputs.branch }}-native-version-bump
#          delete-branch: true
