name: Android

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  android:
    name: Build
    runs-on: ubuntu-latest
    environment: client-${{ inputs.environment }}
    env:
      CI: github

      SOURCEMAPS_DIR: ./build/sourcemaps

      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      DOTENV_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      DOTENV_DEBUG: ${{ secrets.DEBUG }}
      DOTENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      DOTENV_IOS_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.IOS_CODE_PUSH_DEPLOYMENT_KEY }}
      DOTENV_ANDROID_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.ANDROID_CODE_PUSH_DEPLOYMENT_KEY }}
      DOTENV_POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
      DOTENV_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      DOTENV_METRICS_ENDPOINT: ${{ secrets.METRICS_ENDPOINT }}
      DOTENV_STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
      DOTENV_DEEP_LINK_PREFIX: ${{ secrets.DEEP_LINK_SCHEMA }}
      DOTENV_DEEP_LINK_SCHEMA: ${{ secrets.DEEP_LINK_PREFIX }}
      DOTENV_ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
      DOTENV_IOS_APPSTORE_ID: ${{ secrets.IOS_APPSTORE_ID }}

      ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
      ANDROID_FLAVOR: ${{ secrets.ANDROID_FLAVOR }}
      ANDROID_UPLOAD_STORE_PASSWORD: ${{ secrets.ANDROID_UPLOAD_STORE_PASSWORD }}
      ANDROID_UPLOAD_KEY_PASSWORD: ${{ secrets.ANDROID_UPLOAD_KEY_PASSWORD }}
      ANDROID_GOOGLE_PLAY_SERVICE_FILE: ./google-play-service.json

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Use Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create Dotenv File
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: DOTENV_
          directory: ./client

      - name: Create google-play-service.json
        working-directory: ./client
        run: |
          cat > $ANDROID_GOOGLE_PLAY_SERVICE_FILE << EOL
          ${{ secrets.ANDROID_GOOGLE_PLAY_SERVICE_FILE }}
          EOL

      - name: Create google-services.json
        working-directory: ./client/android/app/src
        run: |
          cat > ./$ANDROID_FLAVOR/google-services.json << EOL
          ${{ secrets.ANDROID_GOOGLE_SERVICES_FILE }}
          EOL

      - name: Create release.keystore
        working-directory: ./client/android/app
        run: echo -n "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" | base64 --decode > release.keystore

      - name: Prepare Source Maps Directory
        working-directory: ./client
        run: mkdir -p $SOURCEMAPS_DIR

      - name: Prepare $GIT_COMMIT_SHORT
        working-directory: ./shared
        run: ./scripts/getGitCommitShort.sh >> $GITHUB_ENV

      - name: Cache Shared Dependencies
        id: cache-shared-node-modules
        uses: actions/cache@v2
        with:
          path: ./shared/node_modules
          key: shared-node-modules-${{ hashFiles('./shared/yarn.lock') }}

      - name: Install Shared Dependencies
        if: steps.cache-shared-node-modules.outputs.cache-hit != 'true'
        working-directory: ./shared
        run: yarn

      - name: Cache Content Dependencies
        id: cache-content-node-modules
        uses: actions/cache@v2
        with:
          path: ./content/node_modules
          key: content-node-modules-${{ hashFiles('./content/yarn.lock') }}

      - name: Install Content Dependencies
        if: steps.cache-content-node-modules.outputs.cache-hit != 'true'
        working-directory: ./content
        run: yarn

      - name: Cache Client Dependencies
        id: cache-client-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: client-node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Install Fastlane Dependencies
        working-directory: ./client/fastlane
        run: bundle install

      - name: Build Content
        working-directory: ./content
        run: yarn build

      - name: Build & Upload App
        working-directory: ./client/fastlane
        run: bundle exec fastlane android app

      - name: Generate Source Map
        working-directory: ./client
        run: >
          yarn react-native bundle
          --dev false
          --entry-file index.js
          --platform android
          --bundle-output $SOURCEMAPS_DIR/index.android.bundle
          --sourcemap-output $SOURCEMAPS_DIR/index.android.bundle.map

      - name: Upload Source Map to Sentry
        working-directory: ./client
        run: >
          yarn sentry-cli releases
          files $GIT_COMMIT_SHORT
          upload-sourcemaps
          --dist ${{ secrets.ENVIRONMENT }}
          --strip-prefix $PWD
          $SOURCEMAPS_DIR

      - name: Associate Commits to Sentry Release
        working-directory: ./client
        run: yarn sentry-cli releases set-commits --auto $GIT_COMMIT_SHORT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Android native version bump on ${{ inputs.branch }} (auto generated)
          commit-message: Native Version Bump
          branch: ${{ inputs.branch }}-android-native-version-bump
