name: CodePush

on:
  workflow_dispatch:

jobs:        
  codepush-ios-production:
    name: iOS Production
    uses: ./.github/workflows/codepush-ios.yml
    with:
      environment: Production
    secrets: inherit
    
  codepush-ios-staging:
    name: iOS Staging
    uses: ./.github/workflows/codepush-ios.yml
    with:
      environment: Staging
    secrets: inherit
