name: CodePush

on:
  workflow_call:

jobs:
  ios-production:
    name: iOS Production
    uses: ./.github/workflows/codepush-deploy.yml
    with:
      environment: production
      platform: ios
    secrets: inherit

  ios-staging:
    name: iOS Staging
    uses: ./.github/workflows/codepush-deploy.yml
    with:
      environment: staging
      platform: ios
    secrets: inherit

  android-production:
    name: Android Production
    uses: ./.github/workflows/codepush-deploy.yml
    with:
      environment: production
      platform: android
    secrets: inherit

  android-staging:
    name: Android Staging
    uses: ./.github/workflows/codepush-deploy.yml
    with:
      environment: staging
      platform: android
    secrets: inherit
