name: CodePush ${{ inputs.platform }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: client-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: v14.x.x

      - name: Output secrets to env
        run: ./.github/workflows/scripts/outputSecretsToEnv.sh
        env:
          secrets: ${{ toJSON(secrets) }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Codepush
        working-directory: ./client
        if: ${{ inputs.platform }} == 'android'
        run: >
          yarn appcenter codepush release-react
          --app 29k.org/29k-Cupcake-Android
          --deployment-name ${{ inputs.environment }}
          --disable-duplicate-release-error
        if: ${{ inputs.platform }} == 'ios'
        run: >
          yarn appcenter codepush release-react
          --app 29k.org/29k-Cupcake-iOS
          --deployment-name ${{ inputs.environment }}
          --plist-file ./ios/Supporting/Info.plist
          --xcode-project-file ./ios/twentyninek.xcodeproj
          --disable-duplicate-release-error
