name: CodePush build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    name: CodePush build
    runs-on: ubuntu-20.04
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: v14.x.x

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Codepush
        working-directory: ./client
        run: > 
          yarn appcenter codepush release-react
          --app 29k.org/29k-Cupcake-iOS
          --deployment-name ${{ inputs.environment }}
          --plist-file ./ios/Supporting/${{ inputs.environment }}/${{ inputs.environment }}.plist
          --xcode-project-file ./ios/twentyninek.xcodeproj
          --disable-duplicate-release-error
