name: CodePush

on:
  workflow_dispatch:

jobs:        
  codepush-ios-production:
    uses: ./.github/workflows/codepush-build
    with:
      environment: Production
    secrets: inherit
    
  codepush-ios-staging:
    uses: ./.github/workflows/codepush-build
    with:
      environment: Staging
    secrets: inherit
