name: CodePush

on:
  workflow_dispatch:

env:
  APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
  CLIENT_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.CLIENT_CODE_PUSH_DEPLOYMENT_KEY }}
  CLIENT_ENVIRONMENT: ${{ secrets.CLIENT_ENVIRONMENT }}

jobs:        
  codepush-ios-production:
    uses: ./.github/workflows/codepush-build.yml
    with:
      environment: Production
    secrets: inherit
    
  codepush-ios-staging:
    uses: ./.github/workflows/codepush-build.yml
    with:
      environment: Staging
    secrets: inherit
