name: CMS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: cms-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v18.18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Cache Root Dependencies
        id: cache-root-node-modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('./yarn.lock') }}

      - name: Install Root Dependencies
        if: steps.cache-root-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Cache Shared Dependencies
        id: cache-shared-node-modules
        uses: actions/cache@v2
        with:
          path: ./shared/node_modules
          key: shared-node-modules-${{ hashFiles('./shared/yarn.lock') }}

      - name: Install Shared Dependencies
        if: steps.cache-shared-node-modules.outputs.cache-hit != 'true'
        working-directory: ./shared
        run: yarn

      - name: Cache Content Dependencies
        id: cache-content-node-modules
        uses: actions/cache@v2
        with:
          path: ./content/node_modules
          key: content-node-modules-${{ hashFiles('./content/yarn.lock') }}

      - name: Install Content Dependencies
        if: steps.cache-content-node-modules.outputs.cache-hit != 'true'
        working-directory: ./content
        run: yarn

      - name: Cache Client Dependencies
        id: cache-client-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: client-node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Cache CMS Dependencies
        id: cache-cms-node-modules
        uses: actions/cache@v2
        with:
          path: ./cms/node_modules
          key: cms-node-modules-${{ hashFiles('./cms/yarn.lock') }}

      - name: Install CMS Dependencies
        if: steps.cache-cms-node-modules.outputs.cache-hit != 'true'
        working-directory: ./cms
        run: yarn

      - name: Build Content
        working-directory: ./content
        run: yarn build

      - name: Build CMS
        working-directory: ./cms
        run: yarn build

      - name: Deploy CMS
        run: >
          yarn firebase deploy
          --project ${{ secrets.FIREBASE_PROJECT }}
          --token ${{ secrets.FIREBASE_TOKEN }}
          --only hosting:cupcake-29k-cms
          --non-interactive
