name: CMS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: cms-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Output secrets to env
        run: ./.github/workflows/scripts/outputSecretsToEnv.sh
        env:
          secrets: ${{ toJSON(secrets) }}

      - name: Cache Root Dependencies
        id: cache-root-node-modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('./yarn.lock') }}

      - name: Install Root Dependencies
        if: steps.cache-root-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Cache CMS Dependencies
        id: cache-cms-node-modules
        uses: actions/cache@v2
        with:
          path: ./cms/node_modules
          key: cms-node-modules-${{ hashFiles('./cms/yarn.lock') }}

      - name: Install CMS Dependencies
        if: steps.cache-cms-node-modules.outputs.cache-hit != 'true'
        working-directory: ./cms
        run: yarn

      - name: Build Content
        working-directory: ./content
        run: yarn build

      - name: Deploy CMS
        run: >
          yarn firebase deploy
          --project "${{ secrets.FIREBASE_PROJECT }}" 
          --token "${{ secrets.FIREBASE_TOKEN }}"
          --only hosting:cupcake-29k-cms
          --non-interactive deploy
          --force
