name: CodePush

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: client-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Output secrets to env
        run: ./.github/workflows/scripts/outputSecretsToEnv.sh
        env:
          secrets: ${{ toJSON(secrets) }}

      - name: Cache Client Dependencies
        id: cache-client-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: client-node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Build Content
        working-directory: ./content
        run: yarn build

      - name: Source GIT Commit Hash Env Variable
        working-directory: ./client
        run: . ./scripts/getGitCommitShort.sh

      - name: Codepush Android
        working-directory: ./client
        if: inputs.platform == 'android'
        run: >
          yarn appcenter codepush release-react
          --app 29k.org/29k-Cupcake-Android
          --deployment-name ${{ inputs.environment }}
          --disable-duplicate-release-error

      - name: Codepush iOS
        working-directory: ./client
        if: inputs.platform == 'ios'
        run: >
          yarn appcenter codepush release-react
          --app 29k.org/29k-Cupcake-iOS
          --deployment-name ${{ inputs.environment }}
          --plist-file ./ios/Supporting/Info.plist
          --xcode-project-file ./ios/twentyninek.xcodeproj
          --disable-duplicate-release-error
