name: Main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy-functions-production:
    name: Functions Production
    uses: ./.github/workflows/deploy-functions.yml
    needs: test
    with:
      environment: production
    secrets: inherit

  deploy-functions-staging:
    name: Functions Staging
    uses: ./.github/workflows/deploy-functions.yml
    needs: test
    with:
      environment: staging
    secrets: inherit

  deploy-ios-production:
    name: iOS Production
    uses: ./.github/workflows/deploy-codepush.yml
    needs: deploy-functions-production
    with:
      environment: production
      platform: ios
    secrets: inherit

  deploy-ios-staging:
    name: iOS Staging
    uses: ./.github/workflows/deploy-codepush.yml
    needs: deploy-functions-staging
    with:
      environment: staging
      platform: ios
    secrets: inherit

  deploy-android-production:
    name: Android Production
    uses: ./.github/workflows/deploy-codepush.yml
    needs: deploy-functions-production
    with:
      environment: production
      platform: android
    secrets: inherit

  deploy-android-staging:
    name: Android Staging
    uses: ./.github/workflows/deploy-codepush.yml
    needs: deploy-functions-staging
    with:
      environment: staging
      platform: android
    secrets: inherit
