name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testClient:
    name: "Test Client"
    uses: ./.github/workflow/test.yml
    secrets: inherit
  deployClient:
    name: "Deploy Client"
    uses: ./.github/workflow/codepush.yml
    needs: testClient
    secrets: inherit
