name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy-ios-production:
    name: Deploy iOS Production
    uses: ./.github/workflows/codepush-deploy.yml
    needs: test
    with:
      environment: production
      platform: ios
    secrets: inherit

  deploy-ios-staging:
    name: Deploy iOS Staging
    uses: ./.github/workflows/codepush-deploy.yml
    needs: test
    with:
      environment: staging
      platform: ios
    secrets: inherit

  deploy-android-production:
    name: Deploy Android Production
    uses: ./.github/workflows/codepush-deploy.yml
    needs: test
    with:
      environment: production
      platform: android
    secrets: inherit

  deploy-android-staging:
    name: Deploy Android Staging
    uses: ./.github/workflows/codepush-deploy.yml
    needs: test
    with:
      environment: staging
      platform: android
    secrets: inherit
